import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/pages/components/Header";
import Category from "@/pages/components/Category";
import About from "@/pages/components/About";
import Ourservices from "@/pages/components/Ourservices";

import CallToAction from "@/pages/components/CallToAction";
import Description from "@/pages/components/Description";
import Pricing from "./components/Pricing";
import FrequentlyAskQuestion from "@/pages/components/FrequentlyAskQuestion";
import Footer from "@/pages/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Category />
      <About />
      <Ourservices />
      <CallToAction />
      <Description />
      <Pricing />
      <FrequentlyAskQuestion />
      <Footer />
    </>
  );
}
